name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 3'

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Install Python 3.9
      with:
        python-version: 3.9
        architecture: x64
    - name: Configure git user
      run: |
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
        git config user.password ${{ github.token }}
    - name: Build
      run: ./build.sh
    - name: Deploy
      run: ./deploy.sh
