name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    - id: timestamp
      run: echo "::set-output name=timestamp::$(python3 -c 'from datetime import datetime,timezone; print(datetime.now(timezone.utc).isoformat())')"
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: cache/*
        key: pypi-cache-${{ steps.timestamp.outputs.timestamp }}
        restore-keys: pypi-cache-
    - name: Install build dependencies
      run: python3 -m pip install -r requirements.txt
    - name: Build static site
      env:
        BIGQUERY_TOKEN: ${{ secrets.BIGQUERY_TOKEN }}
      run: python3 update.py -v
    - name: Auto-commit packages.json
      uses: stefanzweifel/git-auto-commit-action@v4.8.0
      with:
        commit_message: "[bot] Update packages.json on ${{ steps.timestamp.outputs.timestamp }}"
        file_pattern: packages.json
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        COMMIT_MESSAGE: "[bot] Deploying from ${{ github.sha }} on ${{ steps.timestamp.outputs.timestamp }}"
        SINGLE_COMMIT: true  # wipe history
